"/":
  enabled: true
  startPermalink: "/intro/"
  sections:
    header_section:
      title: "Mirë se vini në dokumentacionin e eID-së së Kosovës"
      text: > 
        Këtu do të gjeni gjithçka që ju nevojitet për të kuptuar, integruar dhe përdorur sistemin e eID-së së Kosovës, nga specifikimet teknike dhe API-të deri te manualet e përdorimit, udhëzimet për sigurinë dhe praktikat më të mira. Pavarësisht nëse po zhvilloni një shërbim të ri, po integroni nënshkrimin digjital ose thjesht po përdorni eID-në, këtu është pika juaj e fillimit.
      startBtnText: "Let's start"
      featuredMedia: >
        <img fetchpriority="high" width="600" height="400" src="assets/img/home.webp" alt="Kosovo eID Docs" decoding="async" loading="eager" style="display:block;" loading="lazy">
    collections_section:
      enabledInHome: true
      except: ["posts", "tools"] # collection name must be the one from _config.yml[collections]
      itemsToShow: 4
      collectionStartBtnText: "Start here"
      buttonsClass: "btn-primary"
      buttonsTextClass: "text-light"
    mostRecentAndPopular_section:
      recentFilesToShow: 3
      allDocsBtnText: "Documents"
      allCatsBtnText: "Categories"
      allTagsBtnText: "Tags"
      buttonsClass: "btn-warning"
      buttonsTextClass: "text-dark"
    stats_section:
      allDocsBtnText: "Total docs"
      savedDocsBtnText: "Saved docs"
      catsBtnText: "Categories"
      pagesWithCustomsCatsBtnText: "Documents"
      tagsBtnText: "Tags"
      buttonsClass: "btn-primary"
      buttonsTextClass: "text-light"
      buttonsIcon: "bi-arrow-right"