"/":
  enabled: true
  startPermalink: "/intro/"
  sections:
    header_section:
      title: "Welcome to Kosovo eID Documentation"
      text: > 
        Here you’ll find everything you need to understand, integrate, and use the Kosovo eID system — from technical specifications and APIs to user manuals, security guidelines, and best practices. Whether you're building a new service, integrating digital signing, or just using eID, this is your starting point.
      startBtnText: "Overview"
      featuredMedia: >
        <img fetchpriority="high" width="600" height="400" src="assets/img/home.webp" alt="Kosovo eID Docs" decoding="async" loading="eager" style="display:block;" loading="lazy">
    collections_section:
      enabledInHome: true
      except: ["posts", "tools"] # collection name must be the one from _config.yml[collections]
      itemsToShow: 4
      collectionStartBtnText: "Start here"
      buttonsClass: "btn-primary"
      buttonsTextClass: "text-light"
    mostRecentAndPopular_section:
      recentFilesToShow: 3
      allDocsBtnText: "Documents"
      allCatsBtnText: "Categories"
      allTagsBtnText: "Tags"
      buttonsClass: "btn-warning"
      buttonsTextClass: "text-dark"
    stats_section:
      allDocsBtnText: "Total docs"
      savedDocsBtnText: "Saved docs"
      catsBtnText: "Categories"
      pagesWithCustomsCatsBtnText: "Documents"
      tagsBtnText: "Tags"
      buttonsClass: "btn-primary"
      buttonsTextClass: "text-light"
      buttonsIcon: "bi-arrow-right"