"/":
  enabled: true
  startPermalink: "/intro/"
  sections:
    header_section:
      title: "Dobrodošli u dokumentaciju Kosovo eID-a"
      text: > 
        Ovde ćete pronaći sve što vam je potrebno za razumevanje, integraciju i korišćenje sistema Kosovo eID, od tehničkih specifikacija i API-ja do korisničkih uputstava, bezbednosnih smernica i najboljih praksi. Bilo da razvijate novu uslugu, integrišete digitalno potpisivanje ili jednostavno koristite eID, ovo je vaša početna tačka.
      startBtnText: "Let's start"
      featuredMedia: >
        <img fetchpriority="high" width="600" height="400" src="assets/img/home.webp" alt="Kosovo eID Docs" decoding="async" loading="eager" style="display:block;" loading="lazy">
    collections_section:
      enabledInHome: true
      except: ["posts", "tools"] # collection name must be the one from _config.yml[collections]
      itemsToShow: 4
      collectionStartBtnText: "Start here"
      buttonsClass: "btn-primary"
      buttonsTextClass: "text-light"
    mostRecentAndPopular_section:
      recentFilesToShow: 3
      allDocsBtnText: "Documents"
      allCatsBtnText: "Categories"
      allTagsBtnText: "Tags"
      buttonsClass: "btn-warning"
      buttonsTextClass: "text-dark"
    stats_section:
      allDocsBtnText: "Total docs"
      savedDocsBtnText: "Saved docs"
      catsBtnText: "Categories"
      pagesWithCustomsCatsBtnText: "Documents"
      tagsBtnText: "Tags"
      buttonsClass: "btn-primary"
      buttonsTextClass: "text-light"
      buttonsIcon: "bi-arrow-right"